---
title: "ESM 204"
author: "Nicholas Bissonnette"
date: "5/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

Q1.
```{r}
damages_data <- read_csv(here("data", "damages.csv")) %>% clean_names()

warming_data <- read_csv(here("data", "warming.csv")) %>% clean_names()

#explore the data
ggplot(data = damages_data, aes(x = warming, y = damages))+
  geom_point()+
  theme_bw()


```

```{r}
#new viz approach
# plot baseline
ggplot() + 
  geom_point(data = warming_data, aes(x = year, y = warming_baseline), color = "red")+
  xlab('year') +
  ylab('damage')

#plot pulse
ggplot() + 
  geom_point(data = warming_data, aes(x = year, y = warming_pulse), color = "blue") +
  xlab('year') +
  ylab('damage')
```
Now we will need to find the quadratic function for the damages curve

```{r}

#first I will start with a linear model

lm_damages <- lm(formula = damages ~ warming, data = damages_data)
summary(lm_damages)

Call:
lm


```

```{r}
#Make the x variable exponential 
damages_data$warming2 <- damages_data$warming^2

quadratic_model <-lm(damages ~ warming + warming2, data = damages_data)

summary(quadratic_model)
```
```{r}
# Now try and visualize the quadratic function fit
#create sequence of warming values 
warming_values <- seq(1, 6, 10)

#create list of predicted damages levels 
damages_predict <- predict(quadratic_model,list(warming=warming_values, warming2=warming_values^2))

#create scatterplot
plot(damages_data$warming, damages_data$damages, pch=16)

#add predicted ilnes based on quadratic regression model 
lines(warming_values, damages_predict, col= 'blue')

```

